#!/usr/bin/perl
use strict;
# ttycolor - quickly switch colorscheme in the Linux Console / TTY
# Copyright (C) 2010 Magnus Woldrich <trapd00r@trapd00r.se>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
########################################################################
use Getopt::Long;

our ($optColor);
GetOptions('colorscheme:s' => \$optColor);

my %palettes = (
    'trapd00r' => [
      'P01c1c1c', # dark black
      'P81c1c1c', # bright black
      'P9ff6767', # dark red
      'P24d4c4c', # red
      'PAb03b31', # dark green
      'P3ff8f00', # green
      'PBbdf13d', # brown
      'P41165e9', # yellow
      'P41165e9', # dark blue
      'PC5496ff', # blue
      'P589005a', # dark magenta
      'PDb50077', # magenta
      'P6cb1c13', # dark cyan
      'PE6be603', # cyan
      'P7ffffff', # light grey
      'PFdedede', # white
      ],
    'trapd00r2' => [
      'P0000000',
      'P83c3c3c',
      'P9d69300',
      'P25fa123',
      'PAa4008a',
      'P31d90b6',
      'PB686868',
      'P495c749',
      'PCbb005e',
      'P5bb7d00',
      'PD367fc5',
      ],
    'vekin' =>  [
      'P0353535',
      'P8666666',
      'P9ae4747',
      'P2ee6363',
      'PA556b2f',
      'P39acd32',
      'PBdaa520',
      'P4ffc125',
      'PC6f99b4',
      'P57c96b0',
      'PD8b7b8b',
      'P6d8bfd8',
      'PEa7a15e',
      'P7dddddd',
      'PFffffff',
      ],
    'necr0' => [
      'P01C1C1C',
      'P84d4d4d',
      'P1a0c0e0',
      'P96080a0',
      'P26080c0',
      'PA0040a0',
      'P34060c0',
      'PB4060a0',
      'P466AABB',
      'PCAACCBB',
      'P5e0f0f0',
      'PD2060c0',
      'P65E7175',
      'PEA3BABF',
      'P7DDEEDD',
      'PF6C887',
      ],
    'coolio' => [
      'P0333333', 
      'P8666666',
      'P1d15517',
      'P9d11723',
      'P236b217',
      'PA00d56a',
      'P3d1b217',
      'PBffea55',
      'P455aaff',
      'PC1793d1',
      'P5b217d1',
      'PDd11793',
      'P693d1b2',
      'PE17d1b2',
      'P7eeeeee',
      'PFffffff',
      ],

    );

if(!@ARGV){
  print "ttycolor -c colorscheme\n", "colorschemes:\n\n";
  print "$_\n" for sort(keys(%palettes));exit 0}


for my $i(0..15) {
  printf "\033]%s\n", $palettes{$optColor}[$i];
}
